/**
 * INI Renderer Tests
 * 
 * Tests for deterministic output and stable formatting
 */

import { renderIni, renderSimpleIni } from './renderer';
import { IniDocument, IniEntry, RawIniBlock } from './types';

describe('INI Renderer', () => {
  describe('Basic rendering', () => {
    it('should render simple entries', () => {
      const document: IniDocument = {
        entries: [
          {
            section: '',
            key: 'ServerName',
            value: 'My Server',
            isKnown: false,
            leadingComments: [],
          },
        ],
        rawBlocks: [],
        leadingComments: [],
      };

      const rendered = renderIni(document);
      expect(rendered).toBe('ServerName=My Server');
    });

    it('should render entries with sections', () => {
      const document: IniDocument = {
        entries: [
          {
            section: 'ServerSettings',
            key: 'ServerName',
            value: 'My Server',
            isKnown: false,
            leadingComments: [],
          },
        ],
        rawBlocks: [],
        leadingComments: [],
      };

      const rendered = renderIni(document);
      expect(rendered).toContain('[ServerSettings]');
      expect(rendered).toContain('ServerName=My Server');
    });

    it('should render multiple sections', () => {
      const document: IniDocument = {
        entries: [
          {
            section: 'ServerSettings',
            key: 'ServerName',
            value: 'My Server',
            isKnown: false,
            leadingComments: [],
          },
          {
            section: 'GameSettings',
            key: 'DifficultyOffset',
            value: '1.0',
            isKnown: false,
            leadingComments: [],
          },
        ],
        rawBlocks: [],
        leadingComments: [],
      };

      const rendered = renderIni(document);
      expect(rendered).toContain('[ServerSettings]');
      expect(rendered).toContain('[GameSettings]');
    });
  });

  describe('Comment rendering', () => {
    it('should render leading comments', () => {
      const document: IniDocument = {
        entries: [
          {
            section: '',
            key: 'ServerName',
            value: 'My Server',
            isKnown: false,
            leadingComments: ['; This is a comment'],
          },
        ],
        rawBlocks: [],
        leadingComments: [],
      };

      const rendered = renderIni(document);
      expect(rendered).toContain('; This is a comment');
      expect(rendered).toContain('ServerName=My Server');
    });

    it('should render trailing comments', () => {
      const document: IniDocument = {
        entries: [
          {
            section: '',
            key: 'ServerName',
            value: 'My Server',
            isKnown: false,
            leadingComments: [],
            trailingComment: '; Trailing comment',
          },
        ],
        rawBlocks: [],
        leadingComments: [],
      };

      const rendered = renderIni(document);
      expect(rendered).toBe('ServerName=My Server ; Trailing comment');
    });

    it('should render file-level leading comments', () => {
      const document: IniDocument = {
        entries: [],
        rawBlocks: [],
        leadingComments: ['; File header', '; Generated by tool'],
      };

      const rendered = renderIni(document);
      expect(rendered).toContain('; File header');
      expect(rendered).toContain('; Generated by tool');
    });
  });

  describe('Raw blocks rendering', () => {
    it('should render raw blocks', () => {
      const document: IniDocument = {
        entries: [],
        rawBlocks: [
          {
            section: 'ServerSettings',
            rawContent: 'UnknownKey=value',
            lineNumber: 1,
          },
        ],
        leadingComments: [],
      };

      const rendered = renderIni(document);
      expect(rendered).toContain('UnknownKey=value');
    });

    it('should render raw blocks with section headers', () => {
      const document: IniDocument = {
        entries: [],
        rawBlocks: [
          {
            section: 'ServerSettings',
            rawContent: '[ServerSettings]\nUnknownKey=value',
            lineNumber: 1,
          },
        ],
        leadingComments: [],
      };

      const rendered = renderIni(document);
      expect(rendered).toContain('[ServerSettings]');
      expect(rendered).toContain('UnknownKey=value');
    });

    it('should maintain order of raw blocks', () => {
      const document: IniDocument = {
        entries: [],
        rawBlocks: [
          {
            section: '',
            rawContent: 'First=1',
            lineNumber: 1,
          },
          {
            section: '',
            rawContent: 'Second=2',
            lineNumber: 2,
          },
        ],
        leadingComments: [],
      };

      const rendered = renderIni(document);
      const firstIndex = rendered.indexOf('First=1');
      const secondIndex = rendered.indexOf('Second=2');
      expect(firstIndex).toBeLessThan(secondIndex);
    });
  });

  describe('Deterministic ordering', () => {
    it('should sort sections alphabetically', () => {
      const document: IniDocument = {
        entries: [
          {
            section: 'Zebra',
            key: 'Key1',
            value: 'value1',
            isKnown: false,
            leadingComments: [],
          },
          {
            section: 'Alpha',
            key: 'Key2',
            value: 'value2',
            isKnown: false,
            leadingComments: [],
          },
        ],
        rawBlocks: [],
        leadingComments: [],
      };

      const rendered = renderIni(document);
      const alphaIndex = rendered.indexOf('[Alpha]');
      const zebraIndex = rendered.indexOf('[Zebra]');
      expect(alphaIndex).toBeLessThan(zebraIndex);
    });

    it('should sort keys within sections', () => {
      const document: IniDocument = {
        entries: [
          {
            section: 'ServerSettings',
            key: 'Zebra',
            value: 'value1',
            isKnown: false,
            leadingComments: [],
          },
          {
            section: 'ServerSettings',
            key: 'Alpha',
            value: 'value2',
            isKnown: false,
            leadingComments: [],
          },
        ],
        rawBlocks: [],
        leadingComments: [],
      };

      const rendered = renderIni(document);
      const alphaIndex = rendered.indexOf('Alpha=value2');
      const zebraIndex = rendered.indexOf('Zebra=value1');
      expect(alphaIndex).toBeLessThan(zebraIndex);
    });

    it('should place empty section first', () => {
      const document: IniDocument = {
        entries: [
          {
            section: 'ServerSettings',
            key: 'Key1',
            value: 'value1',
            isKnown: false,
            leadingComments: [],
          },
          {
            section: '',
            key: 'Key2',
            value: 'value2',
            isKnown: false,
            leadingComments: [],
          },
        ],
        rawBlocks: [],
        leadingComments: [],
      };

      const rendered = renderIni(document);
      const topLevelIndex = rendered.indexOf('Key2=value2');
      const sectionIndex = rendered.indexOf('[ServerSettings]');
      expect(topLevelIndex).toBeLessThan(sectionIndex);
    });
  });

  describe('renderSimpleIni', () => {
    it('should render simple map structure', () => {
      const data = new Map<string, Map<string, string>>();
      const section1 = new Map<string, string>();
      section1.set('Key1', 'value1');
      section1.set('Key2', 'value2');
      data.set('Section1', section1);

      const rendered = renderSimpleIni(data);
      expect(rendered).toContain('[Section1]');
      expect(rendered).toContain('Key1=value1');
      expect(rendered).toContain('Key2=value2');
    });

    it('should handle empty section', () => {
      const data = new Map<string, Map<string, string>>();
      const topLevel = new Map<string, string>();
      topLevel.set('Key1', 'value1');
      data.set('', topLevel);

      const rendered = renderSimpleIni(data);
      expect(rendered).toBe('Key1=value1');
      expect(rendered).not.toContain('[]');
    });
  });
});

